//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GesNautico.Shared {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class SharedSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SharedSettings defaultInstance = ((SharedSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SharedSettings())));
        
        public static SharedSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public float ValorQuota {
            get {
                return ((float)(this["ValorQuota"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Todos</string>\r\n  <string>Normal</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection EscalaoAtleta {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["EscalaoAtleta"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Masc.</string>\r\n  <string>Fem.</string>\r\n  <string>Indef.</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection Genero {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Genero"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Activo</string>\r\n  <string>Inactivo</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Estado {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Estado"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Activos</string>\r\n  <string>Inactivos</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Estados {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Estados"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Masc.</string>\r\n  <string>Fem.</string>\r\n  <string>Indef.</string>\r\n</Arra" +
            "yOfString>")]
        public global::System.Collections.Specialized.StringCollection Sexos {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Sexos"]));
            }
        }
    }
}
